repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types_or: [yaml, json, markdown]

  - repo: https://github.com/APIDevTools/swagger-cli
    rev: v4.0.4
    hooks:
      - id: swagger-validation
        name: swagger-validate-public-api
        args: ["validate", "doc/openapi/public_api.yml"]
      - id: swagger-validation
        name: swagger-validate-privileged-api
        args: ["validate", "doc/openapi/privileged_api.yml"]
