repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml, json, xml, markdown, scss, javascript]

  - repo: https://github.com/APIDevTools/swagger-cli
    rev: v4.0.4
    hooks:
      - id: swagger-validation
        name: swagger-validate-public-api
        args: ["validate", "doc/openapi/public_api.yml"]
      - id: swagger-validation
        name: swagger-validate-privileged-api
        args: ["validate", "doc/openapi/privileged_api.yml"]

  - repo: local
    hooks:
      - id: optic-diff
        name: Optic
        entry: bash -c 'set -e; for x in "$@"; do optic diff "$x"; done' --
        language: node
        require_serial: true
        additional_dependencies:
          - "@useoptic/optic"
        files: ^doc/openapi/.*\.yml

  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.5.1
    hooks:
      - id: zizmor
