# From a CSV file which has MarkLogic document ids in the first column,
# e.g. generated by https://github.com/nationalarchives/tna-judgments-parser/blob/main/backlog/docs/marklogic-ingested-parser-run.xquery
# create a script that can be uploaded to AWS CloudShell to copy the PDFs
# from the unpublished bucket to the public bucket.

# Note that the buckets here are production buckets.

import csv

import Path

# We assume that the first column of the CSV contains the docid and it looks like "/d-UUID.xml"
with Path.open("files.csv") as f:
    reader = csv.reader(f)
    for row in reader:
        # skip rows that don't look like they contain a docid (e.g. header)
        if ".xml" not in row[0]:
            continue
        docid = row[0].strip("/").strip(".xml")
        print(  # noqa: T201
            f"aws s3 cp s3://tna-caselaw-unpublished-assets/{docid}/{docid}.pdf s3://tna-caselaw-assets/{docid}/{docid}.pdf",
        )
