@startuml
participant Transformation
participant Enrichment
participant AdminUI
participant Marklogic
participant PublicUI

Transformation -> Marklogic: Insert managed document
return OK: v1
Enrichment -> Marklogic: Check out
return OK: v1
Enrichment -> Marklogic: Update
return OK: v2
AdminUI -> Marklogic: Atomic checkout/update/checkin
return DENIED
PublicUI -> Marklogic: Read
return OK: v2
Enrichment -> Marklogic: Update
return OK: v3
Enrichment -> Marklogic: Check in
return OK
AdminUI -> Marklogic: Atomic checkout/update/checkin
return OK: v4
PublicUI -> Marklogic: Read
return OK: v4
@enduml
