@startuml Container Diagram
!include include/c4.puml
!include include/style.puml
!include include/people.puml

System_Ext(transformationEngine, "Transformation Engine")
System_Ext(enrichment, "Enrichment Engine")

System_Boundary(access, "Case Law Access") {
  Container(publicUI, "Public UI", "Django", $sprite="docker")
  Container(editorUI, "Editor UI", "Django", $sprite="docker")
  Container(ingester, "Ingester", "AWS Lambda", $sprite="aws")
  Container(pubsub, "Change Notifications", "AWS SNS", $sprite="aws")
  System_Boundary(markLogicServer, "Marklogic Server") {
    SystemDb(markLogic, "Marklogic", "Document and service metadata store")
    Container(api, "REST API", "Javascript", $tags="Marklogic Application")
    Container(parser, "Alpha Parser", "Jim's parser application, including multi-document support", $tags="Marklogic Application")
    BiRel(api, markLogic, "queries", "XQuery")
    BiRel(parser, markLogic, "queries", "XQuery")
  }
}

Rel(api, pubsub, "publishes change notification")

Rel(transformationEngine, ingester, "sends parsed documents", "S3/SNS")
Rel(ingester, api, "stores documents", "HTTPS")
BiRel(enrichment, api, "reads/writes", "HTTPS")
BiRel(enrichment, pubsub, "subscribes/notifies", "HTTPS")
BiRel(editorUI, api, "reads/writes", "HTTPS")
Rel(publicUI, api, "reads", "HTTPS")
Rel_R(apiUser, api, "reads", "HTTPS")
Rel(joepublic, publicUI, "uses", "HTTPS")
Rel(editor, editorUI, "uses", "HTTPS")
Rel(editor, parser, "uses for advanced ingestion", "HTTPS", $tags="fallback")
Lay_D(apiUser, enrichment)

!include include/display.puml
@enduml
