@startuml Deployment Diagram
!include include/c4.puml
!include include/style.puml

left to right direction

Node(internet, "Internet") {
    !include include/people.puml
    System_Ext(republisher, "Republisher")
}

Node(te, "Transformation Engine", "AWS") {
    System_Ext(te_sns, "SNS", "Notification queue")
    SystemDb_Ext(te_s3, "S3", "File transfer bucket")
    Lay_D(te_sns, te_s3)
}

Node(ee, "Enrichment Engine", "AWS") {
    System_Ext(enrichment, "Enrichment Engine")
}

Node(account, "Case Law System", "AWS"){
    Node(ecs, "Elastic Container Service"){
        Container(publicui, "Public UI", "Django", $sprite="docker")
        Container(editorui, "Editor UI", "Django", $sprite="docker")
        Container(pubsub, "Notifications", $sprite="docker")
        Container(api, "REST API", "Python", $sprite="docker")
    }
    System(api_lb, "Elastic Load Balancing", "Distributes API demand across Marklogic nodes", $sprite="aws")
    Node(ec2, "EC2"){
        Node(marklogic, "Marklogic Server") {
            SystemDb(db, "Marklogic", "Document and service metadata store")
        }
    }
    BiRel(api_lb, db, "proxies", "HTTPS")
    BiRel(api, api_lb, "queries", "HTTPS")
    Node(lambda, "Lambda"){
        Container(ingester, "Ingester", "Javascript", $sprite="aws")
    }
    System(cache, "Cloudfront", "Public UI web cache", $sprite="aws")
    Rel(publicui, api, "reads from", "HTTPS")
    Rel(cache, publicui, "reads from", "HTTPS")
    BiRel(editorui, api, "reads/writes", "HTTPS")
}

BiRel(ingester, te_sns, "subscribes/notifies", "SNS")
Rel(ingester, te_s3, "reads from", "HTTPS")
Rel(ingester, api, "writes to", "HTTPS")

Rel(joepublic, cache, "browses", "HTTPS")

Rel(editor, editorui, "uses", "HTTPS")
Rel(ingester, editor, "notifies", "email")

BiRel(enrichment, api, "reads/writes", "HTTPS/Atom")
BiRel(republisher, api, "reads/writes", "HTTPS/Atom")

BiRel(republisher, pubsub, "subscribes to", "Websub")
BiRel(enrichment, pubsub, "subscribes to", "Websub")
BiRel(editorui, pubsub, "subscribes to", "Websub")
Rel(api, pubsub, "sends updates", "Websub")


!include include/display.puml
@enduml
