@startuml Deployment Diagram
!include include/c4.puml
!include include/style.puml

Node(internet, "Internet") {
    !include include/people.puml
}

Node(te, "Transformation Engine", "AWS") {
    System_Ext(te_sns, "SNS", "Notification queue")
    SystemDb_Ext(te_s3, "S3", "File transfer bucket")
    Lay_D(te_sns, te_s3)
}

Node(ee, "Enrichment Engine", "AWS") {
    System_Ext(enrichment, "Enrichment Engine")
}

Node(account, "Case Law System", "AWS"){
    Node(ecs, "Elastic Container Service"){
        Container(publicui, "Public UI", "Django", $sprite="docker")
        Container(editorui, "Editor UI", "Django", $sprite="docker")
    }
    System(api_lb, "Elastic Load Balancing", "Distributes API demand across Marklogic nodes", $sprite="aws")
    Node(ec2, "EC2"){
        Node(marklogic, "Marklogic Server") {
            SystemDb(db, "Marklogic", "Document and service metadata store")
            Container(api, "REST API", "Javascript", $tags="Marklogic Application")
            BiRel(api, db, "queries", "XQuery")
        }
    }
    BiRel(api_lb, api, "proxies", "HTTPS")
    Node(lambda, "Lambda"){
        Container(parser, "Alpha Parser", "AWS Lambda", $sprite="aws")
        Container(ingester, "Ingester", "Javascript", $sprite="aws")
    }
    System(cache, "Cloudfront", "Public UI web cache", $sprite="aws")
    System(pubsub, "SNS", "Change notifications", $sprite="aws")
    Rel(publicui, api_lb, "reads from", "HTTPS")
    Rel(cache, publicui, "reads from", "HTTPS")
    BiRel(editorui, api_lb, "reads/writes", "HTTPS")
    Rel(api, pubsub, "publishes change notification")
}

BiRel(ingester, te_sns, "subscribes/notifies", "SNS")
Rel(ingester, te_s3, "reads from", "HTTPS")
Rel(ingester, api_lb, "writes to", "HTTPS")

Rel(joepublic, cache, "browses", "HTTPS")

Rel(editor, editorui, "uses", "HTTPS")
BiRel(editorui, parser, "advanced ingestion", "HTTPS")
Rel(ingester, editor, "notifies", "email")

BiRel(enrichment, api_lb, "reads/writes", "HTTPS")
BiRel(enrichment, pubsub, "subscribes/notifies", "SNS")

Rel(apiUser, api_lb, "reads", "HTTPS")

Lay_D(joepublic, editor)
Lay_D(editor, apiUser)

!include include/display.puml
@enduml
