@startuml System Landscape
!include include/c4.puml
!include include/style.puml
!include include/people.puml

System_Ext(tdr, "Transfer Digital Records")
System_Ext(transformationEngine, "Transformation Engine")
System_Ext(enrichment, "Enrichment Engine")
System_Ext(republisher, "Republisher")

System_Boundary(access, "Case Law Access") {
  System(publicUI, "Public UI")
  System(editorUI, "Editor UI")
  System(ingester, "Ingester")
  System(api, "REST API")
  SystemDb(markLogic, "LegalDocML document store", "MarkLogic")
}

BiRel(api, markLogic, "reads/writes", "HTTP/XQuery")

Rel(tdr, transformationEngine, "sends uploaded documents")
Rel(transformationEngine, ingester, "sends parsed documents", "S3/SNS")
Rel(ingester, markLogic, "stores documents", "HTTP/XQuery")
Rel(enrichment, publicUI, "reads", "HTTPS/Atom")
Rel(enrichment, api, "writes", "HTTPS")
BiRel(editorUI, markLogic, "reads/writes", "HTTP/XQuery")
Rel(publicUI, markLogic, "reads", "HTTP/XQuery")
Rel(joepublic, publicUI, "uses", "HTTPS")
Rel(republisher, publicUI, "reads", "HTTPS/Atom")
Rel(editor, editorUI, "uses", "HTTPS")

!include include/display.puml
@enduml
