name: pre-commit
permissions: {}

on:
  pull_request:
    branches: ["main"]

  push:
    branches: ["main"]

  merge_group:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
        env:
          SKIP: no-commit-to-branch
