name: Source safety
permissions: {}
on:
  pull_request:
  push:
jobs:
  secrets:
    name: Check for secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: nationalarchives/tdr-github-actions/.github/actions/run-git-secrets@b98899c2acfaf872e0053671743a5b1284b0dab0 # v0.0.43
