name: Source safety
permissions: {}
on:
  pull_request:
  push:
jobs:
  secrets:
    name: Check for secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: nationalarchives/tdr-github-actions/.github/actions/run-git-secrets@e7b57a3bdf7863c951cd203101c6d566986376e3 # v0.0.38
